### ISSUE TITLE
Theme does not look at all as the sample image

### ISSUE THREAD

**Issue by cesariovb** [Dpschu2/Neon-Future#1]
As the title says, the theme does not look like the sample image.

For me, this is how it looks like:

![Captura de Pantalla 2024-11-13 a la(s) 14 26 05](https://github.com/user-attachments/assets/65e632fc-6e2a-4e6d-948d-44fedf61b41b)

And it should look like the awesome sample pic:

<img width="1800" alt="screen" src="https://github.com/user-attachments/assets/05e741d5-2865-4333-b0d0-c588e616a787">

**Comment by Dpschu2** [comment]
Thanks for pointing this out! I will update this with my updated working settings. Those settings don't work now because the APC+ extension does not work with VSCode's latest version. I will message back once I update the repo.

**Comment by Dpschu2** [comment]
@cesariovb This is now updated. Let me know if you run into issues installing 👍

**Comment by cesariovb** [comment]
> @cesariovb This is now updated. Let me know if you run into issues installing 👍

It works perfectly now, thanks a lot!, this is an awesome theme.

**Comment by cesariovb** [comment]
> @cesariovb This is now updated. Let me know if you run into issues installing 👍

It works perfectly now, thanks a lot!, this is an awesome theme!
